import type { Metadata } from "next";
import { Manrope, Space_Mono } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScroll";
import { ThemeProvider } from "@/providers/ThemeProvider";

const manrope = Manrope({
   variable: '--font-manrope',
   subsets: ['latin']
})

const spaceMono = Space_Mono({
   variable: '--font-space',
   weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${spaceMono.variable} antialiased px-10`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
         <SmoothScrolling>
            {children}
         </SmoothScrolling>
      </ThemeProvider>
      </body>
    </html>
  );
}
